export const products = [
    { id: 'P1', productName: 'Banana', price: 80, productImg: 'https://cdn.pixabay.com/photo/2018/09/24/20/12/bananas-3700718_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P2', productName: 'Tomato', price: 30, productImg: 'https://cdn.pixabay.com/photo/2018/06/17/14/44/tomatoes-3480643__340.jpg', description: 'Lorem Ipsum has been the industry s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P3', productName: 'Potato', price: 50, productImg: 'https://cdn.pixabay.com/photo/2016/08/11/08/49/potatoes-1585075_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P4', productName: 'cabedgh', price: 20, productImg: 'https://media.istockphoto.com/id/1328561636/photo/white-cabbage-on-wooden-table.jpg?s=2048x2048&w=is&k=20&c=gQCWtl8Woa9OriP2pTGMD_U-LbqwMOeAQ0qexXqzB0w=', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P5', productName: 'Eggs', price: 35, productImg: 'https://cdn.pixabay.com/photo/2022/07/26/13/55/egg-7345934_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P6', productName: 'milk', price: 170, productImg: 'https://cdn.pixabay.com/photo/2018/06/17/14/44/tomatoes-3480643__340.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,'},
    { id: 'P7', productName: 'Fries', price: 10, productImg: 'https://cdn.pixabay.com/photo/2014/11/05/16/35/milk-518067_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    
];

export default products;