export const products = [
    { id: 'P13', productName: 'Chips', price: 50, productImg: 'https://www.eatthis.com/wp-content/uploads/sites/4/2019/04/smoked-paprika-potato-chips.jpg?quality=82&strip=1', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P12', productName: 'Fries', price: 70, productImg: 'https://c.ndtvimg.com/2021-03/s8q2h2po_french-fries_625x300_17_March_21.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P11', productName: 'Coockies', price: 100, productImg: 'https://www.couponraja.in/theroyale/wp-content/uploads/2017/07/britannia-1.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P14', productName: 'Butter', price: 170, productImg: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/202211/Amul%20Butter-2-sixteen_nine_0.png?VersionId=tyZHTpxOL.EPfxCAZiQUz06AibL7v44q', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P15', productName: 'Cadbury', price: 50, productImg: 'https://cdn.togetherv.com/cadbury-chocolates-hamper-sub2_1655983765.webp', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P1', productName: 'Banana', price: 40, productImg: 'https://cdn.pixabay.com/photo/2018/09/24/20/12/bananas-3700718_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P2', productName: 'Tomato', price: 30, productImg: 'https://cdn.pixabay.com/photo/2018/06/17/14/44/tomatoes-3480643__340.jpg', description: 'Lorem Ipsum has been the industry s standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P3', productName: 'Potato', price: 50, productImg: 'https://cdn.pixabay.com/photo/2016/08/11/08/49/potatoes-1585075_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P4', productName: 'cabedgh', price: 20, productImg: 'https://media.istockphoto.com/id/1328561636/photo/white-cabbage-on-wooden-table.jpg?s=2048x2048&w=is&k=20&c=gQCWtl8Woa9OriP2pTGMD_U-LbqwMOeAQ0qexXqzB0w=', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P5', productName: 'Eggs', price: 35, productImg: 'https://cdn.pixabay.com/photo/2022/07/26/13/55/egg-7345934_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P6', productName: 'milk', price: 70, productImg: 'https://cdn.pixabay.com/photo/2014/11/05/16/35/milk-518067_960_720.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,'},
    { id: 'P7', productName: 'Mango', price: 150, productImg: 'https://cdn.pixabay.com/photo/2013/11/20/23/02/king-mango-214269__340.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P8', productName: 'Apple', price: 200, productImg: 'https://cdn.pixabay.com/photo/2015/06/10/19/56/apples-805124__340.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P9', productName: 'Sauces', price: 100, productImg: 'https://hips.hearstapps.com/hmg-prod/images/marinara-sauce-bottles-215-1547064355.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    { id: 'P10', productName: 'Peanut Butter', price: 280, productImg: 'https://assets.bonappetit.com/photos/63409999c6b2a3464a5c9bf3/16:9/w_2560%2Cc_limit/1007-pb-taste-test-lede.jpg', description: 'Lorem Ipsum has been the industrys standard dummy text ever since the 1500s when an unknown printer took a galley of type and scrambled it to make a type specimen book.', vendor: 'There are many variations of passages of Lorem Ipsum available,' },
    ];

export default products;